services:
  playwright:
    image: localhost/devcontainer-trustify-e2e:latest
    build:
      dockerfile: ./Dockerfile
    security_opt:
      - "label=disable"
    userns_mode: "keep-id"
    network_mode: host
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ${TRUSTIFY_UI_PATH:-~/git/guacsec/trustify-ui}:/workspace:cached
